version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: saputraarel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.2-python3.10
    container_name: airflow-webserver
    command: webserver
    restart: always
    depends_on:
      - postgres
      - airflow-scheduler
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: wrOJHegI5HtlSC4q9w03I0oy6AoA5lSpILH8fjPSpUU=
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./sql:/opt/airflow/sql
      - ./reports:/opt/airflow/reports
      - ./scripts:/opt/airflow/scripts
      - ./datasets:/opt/airflow/datasets
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8082:8080'

  airflow-scheduler:
    image: apache/airflow:2.9.2-python3.10
    container_name: airflow-scheduler
    command: scheduler
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: wrOJHegI5HtlSC4q9w03I0oy6AoA5lSpILH8fjPSpUU=
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./reports:/opt/airflow/reports
      - ./scripts:/opt/airflow/scripts
      - ./datasets:/opt/airflow/datasets
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
      - /etc/localtime:/etc/localtime:ro
      - ./sql:/opt/airflow/sql

  airflow-init:
    image: apache/airflow:2.9.2-python3.10
    container_name: airflow-init
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      pip install --no-cache-dir -r /requirements.txt
      "
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - '3000:3000'
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
  minio_data:
  metabase-data:
